[package]
name = "local-lore"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "=1.0.145"
turbomcp = "=2.0.2"
tokio = { version = "=1.48.0", features = ["full"] }
turbomcp-protocol = "=2.0.2"
turbomcp-server = "=2.0.2"
