[package]
name = "local-lore"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
surrealdb = { version = "=2.3.10", features = ["kv-rocksdb"] }
surrealdb-migrations = "=2.3.0"
tokio = { version = "=1.48.0", features = ["full"] }
turbomcp = "=2.0.2"
turbomcp-protocol = "=2.0.2"
turbomcp-server = "=2.0.2"
